include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - cancel_subscriptions
    - close_sinks
    - test_types_in_equals
    - unawaited_futures
    - unnecessary_statements